local loader = {}
loader.Game =
{
  ["_currentTurn"] = 1,
  ["_uidCounter"] = 5,
  ["currentPlayer"] = nil --[[ function ]],
  ["getPlayerFromIndex"] = nil --[[ function ]],
  ["getUID"] = nil --[[ function ]],
  ["load"] = nil --[[ function ]],
  ["new"] = nil --[[ function ]],
  ["nextTurn"] = nil --[[ function ]],
  ["struct"] = "Game",
}

loader.Box =
{
  ["load"] = nil --[[ function ]],
  ["meeples"] = {
    [1] = {
      ["color"] = "red",
      ["label"] = "P1",
      ["load"] = nil --[[ function ]],
      ["moveTo"] = nil --[[ function ]],
      ["name"] = "player",
      ["new"] = nil --[[ function ]],
      ["pos"] = "Garden",
      ["struct"] = "Meeple",
      ["uid"] = 1,
      ["x"] = -1,
      ["y"] = -1,
    },
    [2] = {
      ["color"] = "green",
      ["label"] = "P2",
      ["load"] = nil --[[ function ]],
      ["moveTo"] = nil --[[ function ]],
      ["name"] = "player",
      ["new"] = nil --[[ function ]],
      ["pos"] = "Main Hall",
      ["struct"] = "Meeple",
      ["uid"] = 2,
      ["x"] = -1,
      ["y"] = -1,
    },
    [3] = {
      ["color"] = "blue",
      ["label"] = "P3",
      ["load"] = nil --[[ function ]],
      ["moveTo"] = nil --[[ function ]],
      ["name"] = "player",
      ["new"] = nil --[[ function ]],
      ["pos"] = "",
      ["struct"] = "Meeple",
      ["uid"] = 3,
      ["x"] = -1,
      ["y"] = -1,
    },
    [4] = {
      ["color"] = "yellow",
      ["label"] = "P4",
      ["load"] = nil --[[ function ]],
      ["moveTo"] = nil --[[ function ]],
      ["name"] = "player",
      ["new"] = nil --[[ function ]],
      ["pos"] = "",
      ["struct"] = "Meeple",
      ["uid"] = 4,
      ["x"] = -1,
      ["y"] = -1,
    },
    [5] = {
      ["label"] = "green",
      ["load"] = nil --[[ function ]],
      ["moveTo"] = nil --[[ function ]],
      ["name"] = "place",
      ["new"] = nil --[[ function ]],
      ["pos"] = "",
      ["struct"] = "Meeple",
      ["uid"] = 5,
      ["x"] = -1,
      ["y"] = -1,
    },
  },
  ["new"] = nil --[[ function ]],
  ["struct"] = "Box",
}

loader.Players =
{
  [1] = {
    ["fear"] = {
      ["incValue"] = 1,
      ["max"] = 4,
      ["min"] = 0,
      ["struct"] = "Counter",
      ["value"] = 3,
    },
    ["inPlay"] = true,
    ["index"] = 0,
    ["load"] = nil --[[ function ]],
    ["meeples"] = {
      [1] = {
        ["color"] = "red",
        ["label"] = "P1",
        ["name"] = "player",
        ["pos"] = "Garden",
        ["struct"] = "Meeple",
        ["uid"] = 1,
        ["x"] = -1,
        ["y"] = -1,
      },
    },
    ["new"] = nil --[[ function ]],
    ["repeatTurn"] = 0,
    ["skipTurn"] = 0,
    ["struct"] = "Player",
  },
  [2] = {
    ["fear"] = {
      ["incValue"] = 1,
      ["max"] = 4,
      ["min"] = 0,
      ["struct"] = "Counter",
      ["value"] = 3,
    },
    ["inPlay"] = true,
    ["index"] = 0,
    ["load"] = nil --[[ function ]],
    ["meeples"] = {
      [1] = {
        ["color"] = "green",
        ["label"] = "P2",
        ["name"] = "player",
        ["pos"] = "Main Hall",
        ["struct"] = "Meeple",
        ["uid"] = 2,
        ["x"] = -1,
        ["y"] = -1,
      },
    },
    ["new"] = nil --[[ function ]],
    ["repeatTurn"] = 0,
    ["skipTurn"] = 0,
    ["struct"] = "Player",
  },
  ["struct"] = "Players",
}

return loader