local loader = {}
loader.Game =
{
  ["_currentTurn"] = 1,
  ["_uidCounter"] = 5,
  ["new"] = nil --[[ function ]],
  ["struct"] = "Game",
  ["load"] = nil --[[ function ]],
  ["getUID"] = nil --[[ function ]],
}

loader.Players =
{
  [1] = {
    ["inPlay"] = true,
    ["index"] = 0,
    ["meeples"] = {
      [1] = {
        ["new"] = nil --[[ function ]],
        ["load"] = nil --[[ function ]],
        ["uid"] = 1,
        ["pos"] = "Garden",
        ["moveTo"] = nil --[[ function ]],
        ["color"] = "red",
        ["name"] = "player",
        ["struct"] = "Meeple",
        ["x"] = -1,
        ["y"] = -1,
        ["label"] = "P1",
      },
    },
    ["fear"] = {
      ["dec"] = nil --[[ function ]],
      ["load"] = nil --[[ function ]],
      ["onMax"] = nil --[[ function ]],
      ["inc"] = nil --[[ function ]],
      ["max"] = 4,
      ["struct"] = "Counter",
      ["min"] = 0,
      ["incValue"] = 1,
      ["value"] = 3,
      ["init"] = nil --[[ function ]],
    },
    ["struct"] = "Player",
    ["load"] = nil --[[ function ]],
    ["new"] = nil --[[ function ]],
    ["repeatTurn"] = 0,
    ["skipTurn"] = 0,
  },
  [2] = {
    ["inPlay"] = true,
    ["index"] = 0,
    ["meeples"] = {
      [1] = {
        ["new"] = nil --[[ function ]],
        ["load"] = nil --[[ function ]],
        ["uid"] = 2,
        ["pos"] = "Main Hall",
        ["moveTo"] = nil --[[ function ]],
        ["color"] = "green",
        ["name"] = "player",
        ["struct"] = "Meeple",
        ["x"] = -1,
        ["y"] = -1,
        ["label"] = "P2",
      },
    },
    ["fear"] = {
      ["dec"] = nil --[[ function ]],
      ["load"] = nil --[[ function ]],
      ["onMax"] = nil --[[ function ]],
      ["inc"] = nil --[[ function ]],
      ["max"] = 4,
      ["struct"] = "Counter",
      ["min"] = 0,
      ["incValue"] = 1,
      ["value"] = 3,
      ["init"] = nil --[[ function ]],
    },
    ["struct"] = "Player",
    ["load"] = nil --[[ function ]],
    ["new"] = nil --[[ function ]],
    ["repeatTurn"] = 0,
    ["skipTurn"] = 0,
    },
  ["struct"] = "Players",
  ["load"] = nil --[[ function ]],
  ["new"] = nil --[[ function ]],
}

loader.Box =
{
  ["new"] = nil --[[ function ]],
  ["struct"] = "Box",
  ["load"] = nil --[[ function ]],
  ["meeples"] = {
    [1] = {
      ["new"] = nil --[[ function ]],
      ["load"] = nil --[[ function ]],
      ["uid"] = 1,
      ["pos"] = "Garden",
      ["moveTo"] = nil --[[ function ]],
      ["color"] = "red",
      ["name"] = "player",
      ["struct"] = "Meeple",
      ["x"] = -1,
      ["y"] = -1,
      ["label"] = "P1",
    },
    [2] = {
      ["new"] = nil --[[ function ]],
      ["load"] = nil --[[ function ]],
      ["uid"] = 2,
      ["pos"] = "Main Hall",
      ["moveTo"] = nil --[[ function ]],
      ["color"] = "green",
      ["name"] = "player",
      ["struct"] = "Meeple",
      ["x"] = -1,
      ["y"] = -1,
      ["label"] = "P2",
    },
    [3] = {
      ["new"] = nil --[[ function ]],
      ["load"] = nil --[[ function ]],
      ["uid"] = 3,
      ["pos"] = "",
      ["moveTo"] = nil --[[ function ]],
      ["color"] = "blue",
      ["name"] = "player",
      ["struct"] = "Meeple",
      ["x"] = -1,
      ["y"] = -1,
      ["label"] = "P3",
    },
    [4] = {
      ["new"] = nil --[[ function ]],
      ["load"] = nil --[[ function ]],
      ["uid"] = 4,
      ["pos"] = "",
      ["moveTo"] = nil --[[ function ]],
      ["color"] = "yellow",
      ["name"] = "player",
      ["struct"] = "Meeple",
      ["x"] = -1,
      ["y"] = -1,
      ["label"] = "P4",
    },
    [5] = {
      ["new"] = nil --[[ function ]],
      ["load"] = nil --[[ function ]],
      ["pos"] = "",
      ["moveTo"] = nil --[[ function ]],
      ["uid"] = 5,
      ["name"] = "place",
      ["struct"] = "Meeple",
      ["x"] = -1,
      ["y"] = -1,
      ["label"] = "green",
    },
  },
}

return loader
