name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0

      - name: Test Project
        run: |
          cmake --build build --config Release
          ctest --test-dir build -C Release -V
